from adom_constants import *

NAME = "Chaos"
SEX = MALE
CLASS = CL_CHAOS_KNIGHT
RACE =  R_DRAKELING
TALENTS = [T_ALERT,
           T_MISER,
           T_TREASURE_HUNTER,
           T_BOON_TO_FAMILY,
           T_HARDY,
           T_TOUGH_SKIN]

#GOOD_CORRUPTIONS = [COR_ASTRAL_SPACE, COR_GROWN_ANTENNAE, COR_FRAGILE_STILTS]
#GOOD_CORRUPTIONS = [COR_ASTRAL_SPACE,COR_GROWN_ANTENNAE,COR_ORDER_FLESH]
GOOD_CORRUPTIONS = [COR_ASTRAL_SPACE,COR_CORRUPTED_TISSUE,COR_ACID_BLOOD]
BAD_CORRUPTIONS = [COR_MANA_BATTERY, COR_UNHOLY_AURA, COR_STIFF_MUSCLES]
#TALENT_COUNT = 2

LE = 10
#STARSIGN = "Candle"

#ITEMS = [(ITEM_RING, r'ring[s]? of djinni')]
