# Player accomplishments
:no_skip
:yellow
have just completed your current quest.
Congratulations! You advance to level %d.

# Beneficial date effects
You feel that starting your adventure on Creator's Day was a good idea.
A lone star leads you to this remote valley.
You feel well prepared for the coming year.
You feel treated.

# Stat gain
:no_skip
:light green
Your muscles feel stronger.
You suddenly feel stronger!
You feel studious.
Your will seems inflexible.
Your movements are getting swifter.
Your health increases.
You feel very self-confident.
Your looks improve.
You feel more in touch with the world.
Your senses sharpen.
feel good about your %s potential.
feel very good about your %s level.

# Stat loss
:no_skip
:red
You feel as if this was not a good idea!
Your muscles soften.
Thinking seems to get tougher.
You feel soft-hearted.
You are getting shaky.
It seems that you are getting a cold.
You feel reserved.
You are growing a wart.
You are getting out of touch with everything.
You seem to get less perceptive.
You feel weak!
You feel exhausted!
You suddenly age!

# Skill gain
:no_skip
:light blue
Your '%s' skill increases by %+d
to %d.
improve in the area of '%s' (from %s to
%s).
improve your skill in the shield group to level %d.
improve your skill in the '%s' weapon group to level %d.
improve your skill with the '%s' weapon category to level %d.
become more efficient in using the '%s' spell (now %+d).

# Equipment damage/destruction
:no_skip
:red
Your %s are destroyed.
Your %s are damaged.
Your %s corrodes!
Your %s corrode!
It is destroyed.
They are destroyed.
Your weapon breaks!
Your %s %s damaged.
Your %s %s destroyed!
Your %s rust%s!
%lld %sof your %s %s!
Your %s %s!
Your %s is finally damaged beyond repair!
The %s on the floor melts down into a puddle of metal!
The %s %s %s!
The %s %s transformed into a rusty heap!
The %s rust%s!
It is annihilated!
They are annihilated!

# Detrimental date effects
You feel unlucky.
You feel slightly exhausted today.

# Food rotting
:no_skip
:brown
Your equipment seems to become smelly.
Your equipment suddenly seems to weigh less.
Your %s rots away!
Your %s starts to rot!
Your %s slowly rots away!
notice %s %s rotting away.

# Spell effect messages
:no_skip
:cyan
You feel your spirits rise!
You feel your spirits soar!
Your mood darkens.
Your eyes itch.
Your eyesight adjusts to normality once more.
You feel like Atlas himself.
You feel your great strength waning.
Suddenly your extraordinary carrying capacity fails you.
Suddenly everything around you seems to speed up!
Suddenly everything around you seems to slow down.
Suddenly you can't see yourself!
For a moment you were gone... then your eyes adjust.
Suddenly you can see yourself again!

# Unnecessary messages
:suppress
Select the companion you want to issue an order to.
Select the slave to command.
#(easily cutting through %s armor with the %s)
#You lust for blood!
#The %s returns!
#You manage to catch it.
#You fail to catch it.
